"""
schemas.py
----------
Pydantic models defining the API request and response contracts.

These schemas serve as the single source of truth for data validation,
serialization, and API documentation (auto-generated by FastAPI).
"""

from typing import Optional
from pydantic import BaseModel, Field


class SearchRequest(BaseModel):
    """Incoming search request from the frontend."""
    query: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Plain text search query. May contain title, author, keywords, or noise.",
        examples=["tolkien hobbit illustrated deluxe 1937", "dickens tale two cities"],
    )


class ExtractedFields(BaseModel):
    """Structured fields extracted from the messy blob by Claude AI."""
    title: Optional[str] = Field(default=None, description="Extracted or inferred book title.")
    author: Optional[str] = Field(default=None, description="Extracted or inferred author name.")
    keywords: list[str] = Field(default_factory=list, description="Additional keywords that may help identify the book.")


class BookCandidate(BaseModel):
    """A single book candidate returned to the frontend."""
    title: str = Field(..., description="Book title from Open Library.")
    author: str = Field(..., description="Primary author name. Contributors are excluded.")
    first_publish_year: Optional[int] = Field(default=None, description="Year the book was first published.")
    open_library_id: Optional[str] = Field(default=None, description="Open Library work identifier.")
    open_library_url: Optional[str] = Field(default=None, description="Direct URL to the book on Open Library.")
    cover_url: Optional[str] = Field(default=None, description="URL to the book cover image.")
    explanation: str = Field(..., description="One-sentence explanation of why this book was matched.")


class SearchResponse(BaseModel):
    """API response containing an ordered list of book candidates."""
    query: str = Field(..., description="Original query submitted by the user.")
    extracted_fields: ExtractedFields = Field(..., description="Fields extracted from the query by Claude AI.")
    candidates: list[BookCandidate] = Field(default_factory=list, description="Ordered list of book candidates.")
    total_results: int = Field(default=0, description="Total number of candidates found before truncation.")


class ErrorResponse(BaseModel):
    """Standardized error response for API consumers."""
    detail: str = Field(..., description="Human-readable error message.")
    error_code: Optional[str] = Field(default=None, description="Machine-readable error code.")
